### ISSUE TITLE
HOL Issue: Storage Acct Creation

### ISSUE THREAD

**Issue by brharr** [Microsoft/MCW-Serverless-architecture#1]
In the very first step in the pre-requisites it says to build a Storage account with the Blog Type and Hot Tier specified. However, further down it says after copying down the access keys, it says to go to the Containers setting under General Settings, however there is no such place within any of the available Storage Account types. This needs to be resolved before the Ready event coming up. 

This should actually be using the "Browse Blobs" settings under the Blobs heading.

Brian

**Comment by joelhulen** [comment]
The only thing that's constant with the Azure portal is change :)

You're right that the setting header is no longer "Settings", but is now called "Blob Service". 
![image](https://user-images.githubusercontent.com/5950304/41567340-b904f918-732d-11e8-8995-58bc5ee29c5b.png)

I think this lab is currently due for a test/fix. I'll find out who's doing that and see if they can update accordingly.

**Comment by ZoinerTejada** [comment]
Thanks Brian. This has been fixed in the june-2018-test-fix branch and will soon be made available in the master branch (before Ready).
