### ISSUE TITLE
Task 2: Run ARM template to provision lab resources

### ISSUE THREAD

**Issue by PremalathaRajendran1** [microsoft/MCW-Serverless-architecture#113]
We are unable to fetch the customized deployment template while following task 2 step 6.

[Serverless architecture before the hands-on lab setup guide]-[Task 2: Run ARM template to provision lab resources]-Now, on the custom deployment screen in the Azure portal, enter the following:

![Custtomized template](https://user-images.githubusercontent.com/99088477/153106071-9905f296-4a4d-46dc-8201-8ce9c2856b5f.PNG)

https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Serverless%20architecture.md#task-2-run-arm-template-to-provision-lab-resources.

**Comment by sadukie** [comment]
@PremalathaRajendran1 What is the error that you are getting when you run the deployment template?

I notice you mentioned [Task 2, Step 6](https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Serverless%20architecture.md#task-2-run-arm-template-to-provision-lab-resources).

Does your **Basics** section look something like this?
![image](https://user-images.githubusercontent.com/106202/153218491-a1051df7-8578-4437-aa83-9c643c97e756.png)

If you see those fields, then you should have the correct ARM template selected.

**Comment by PremalathaRajendran1** [comment]
@sadukie

Please find the below screenshot, Basic is disabled, and Unable to use it.

https://portal.azure.com/#create/Microsoft.Template
![Customized](https://user-images.githubusercontent.com/99088477/153320053-5a57408d-a9c0-4c5c-8c29-62c4d2e74093.PNG)


Please help us to use the customized template.

**Comment by sadukie** [comment]
@PremalathaRajendran1 I'm not sure what you mean about navigating to deploy it and sharing the video.

Have you tried clicking on the "Deploy to Azure" image? It should take you to here: [Deploy the MCW Serverless Architecture resources to Azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2FMCW-Serverless-architecture%2Fmain%2FHands-on%20lab%2Flab-files%2Farm-template%2Fazure-deploy.json).

Once you click that link, it will get you through [Before the Hands-on Lab, Task 2, Step 1.](https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Serverless%20architecture.md#task-2-run-arm-template-to-provision-lab-resources),

**Comment by PremalathaRajendran1** [comment]
@ [sadukie](https://github.com/sadukie)

Thanks for your prompt response, When we tried to deploy through custom deployment, we are getting the below errors.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InUseSubnetCannotBeUpdated","message":"Subnet default is in use and cannot be updated."}]}


![Deployment error](https://user-images.githubusercontent.com/99088477/153694893-bb81750a-103f-4639-8b71-12786c4ab34e.PNG)


Please do the needful.

**Comment by sadukie** [comment]
@PremalathaRajendran1 Have you tried deleting all the resources from failed attempts and running through the ARM template again? Are you still running into issues?

**Comment by DawnmarieDesJardins** [comment]
No further comments from field, closing issue.  Please re-open if needed.
