### ISSUE TITLE
Before the HOL - ObjectId not returned

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Serverless-architecture#115]
With the [Before the HOL](../blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Serverless%20architecture.md) documentation, the user objectId is needed to pass it as parameter to the ARM template. The specified command no longer returns the `objectId`. Instead, the ìd` can be used:

Task 2, Step 3:

Using the command

```bash
az ad signed-in-user show --query objectId -o tsv
```

doesn't return an `objectId`, the result is empty. Instead, this command can be used:

```bash
az ad signed-in-user show --query id -o tsv
```

**Comment by saimachi** [comment]
Hi @christiannagel,

Thanks for bringing this issue to our attention. I updated the CLI command text and a few screenshots in the Pre-HOL document.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with latest commit.
