### ISSUE TITLE
Computer Vision Service always  returns 404...

### ISSUE THREAD

**Issue by fawohlsc** [Microsoft/MCW-Serverless-architecture#14]
… which can be fixed by using _"https://westeurope.api.cognitive.microsoft.com/vision**/v2.0/ocr**"_ instead of _"https://westeurope.api.cognitive.microsoft.com/vision**/v1.0**"_ as _"computerVisionApiUrl"_ in Application settings. Seems like Azure Portal shows the wrong endpoint URL... :-)

**Comment by DawnmarieDesJardins** [comment]
Assigned to Joel - Please review this issue for us.
Thanks! Dawnmarie

**Comment by givenscj** [comment]
Updated to reference the new v2 endpoint.
