### ISSUE TITLE
Issue in Exercise 3 task 3.2

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-Serverless-architecture#15]
Needs the updated lab guide. There is lots of update in Azure. 
Azure Function integration service is not showing Cosmos DB as an option of +New Output.
See the attached screenshot. Cosmos DB option is not there in the new output section.
![snag_22f97c29](https://user-images.githubusercontent.com/27498287/46013853-0e9fc780-c0eb-11e8-99dd-5e2e5210df87.png)

https://github.com/Microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-3-add-an-azure-cosmos-db-output-to-the-saveplatedata-function

**Comment by akn9050** [comment]
Any update on this

**Comment by givenscj** [comment]
Hi there,  I just ran through this and I do see Azure Cosmos DB on the Integrate tab.  I can't know for sure, and this may not help, but possibly you have an older tenant and need to enable those resources in it for cosmos db to show up?
