### ISSUE TITLE
Custom topic sub error

### ISSUE THREAD

**Issue by oyuksektepeli** [Microsoft/MCW-Serverless-architecture#21]
When i do as in lab and subscribe savePlateData and queuePlateForManualCheckup, savePlateData documents are not written to cosmos. When i subscribe to all Events it is working. queuePlateForManualCheckup has no problem. But savePlateData event not working.

**Comment by DawnmarieDesJardins** [comment]
Assigning to Chris for review.

**Comment by DawnmarieDesJardins** [comment]
Thanks Onur!  We just completed a review of this workshop with updates to the lab.  Please let us know if there's anything else you see needs updated.  We appreciate your help keeping us current.
