### ISSUE TITLE
Screenshots are very old. Need to update.

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-Serverless-architecture#22]
1. In [Exercise 1- Task 2.4](https://github.com/Microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-provision-the-function-apps) need to change screenshot for **Create Function App** blade. Now, we have to select Runtime Stack(Language) during create Function App. For TollBoothEvents function need to select **Java Script** for  Runtime Stack. 
![snag_1dd9e9c5](https://user-images.githubusercontent.com/27498287/48840001-5bceab80-edb3-11e8-95b0-203522619fa1.png)
1. For the second function **TollBoothFunctionApp** choose **.NET** for Runtime Stack option. 
1. In [Exercise 3- Task 1](https://github.com/Microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-create-function-to-save-license-plate-data-to-azure-cosmos-db): UI for adding Event Grid Trigger is changed. Please add new screenshots.
1. Also please re-validate the lab and update necessary changes.
1. Please update the lab guide and let me know when it will be ready.

**Comment by waltermyersiii** [comment]
@DawnmarieDesJardins?

**Comment by DawnmarieDesJardins** [comment]
Hi Amit!  We just completed a test/fix on the workshop and many of the screenshots have been update.  Please keep letting us know if you find something that needs to be updated.

**Comment by GhumanNavneet** [comment]
Nothing is updated in lab. Please work on it

**Comment by DawnmarieDesJardins** [comment]
@joelhulen @givenscj 
Hi gentlemen,
Not sure who's currently working on this one.  Reopening the issue, can you please verify that the lab screenshots are correct?  We just went through a test/fix so they would have been updated then, yes?

**Comment by joelhulen** [comment]
@DawnmarieDesJardins Yes, they usually are updated in test/fixes. I will go through and update this week.

**Comment by givenscj** [comment]
Updated in latest nov branch.
