### ISSUE TITLE
Link to MCW in related reference section

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-Serverless-architecture#23]
Let's add a link to [Microsoft/MCW](https://github.com/Microsoft/MCW) in the related reference like other workshops 

![image](https://user-images.githubusercontent.com/5002831/48840556-718aa380-eda8-11e8-8180-668652ede54a.png)

**Comment by DawnmarieDesJardins** [comment]
Addressed in the Nov test/fix.  Closing issue, thank you Hosam!
