### ISSUE TITLE
git project shouldn't include console app

### ISSUE THREAD

**Issue by adhurwit** [Microsoft/MCW-Serverless-architecture#24]
If you commit and push the git project to github, then you get a storage key in your github public repo

**Comment by waltermyersiii** [comment]
@joelhulen?

**Comment by DawnmarieDesJardins** [comment]
@joelhulen 
Any update?  Thank you! Dawnmarie

**Comment by joelhulen** [comment]
I'll update to exclude the config. We still want the console app as part of the solution.

**Comment by givenscj** [comment]
Quick fix: Added steps to tell lab actor to delete the repo after labs are completed in nov-2018-testfix.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, updated and merged to master
