### ISSUE TITLE
Please work on following issues:

### ISSUE THREAD

**Issue by GhumanNavneet** [Microsoft/MCW-Serverless-architecture#27]
In Exercise 1- Task 2.4 need to change screenshot for Create Function App blade. Now, we have to select Runtime Stack(Language) during create Function App. For TollBoothEvents function need to select Java Script for Runtime Stack.
snag_1dd9e9c5
For the second function TollBoothFunctionApp choose .NET for Runtime Stack option.
In Exercise 3- Task 1: UI for adding Event Grid Trigger is changed. Please add new screenshots.
Also please re-validate the lab and update necessary changes.
Please update the lab guide and let me know when it will be ready.

**Comment by givenscj** [comment]
Fixed in latest nov-2018-testfix.
