### ISSUE TITLE
How to deploy the function app directly from VS

### ISSUE THREAD

**Issue by yeahsicy** [Microsoft/MCW-Serverless-architecture#30]
Currently, the function app project seems a bit old at https://github.com/Microsoft/MCW-Serverless-architecture/tree/master/Hands-on%20lab/starter

If you directly deploy from VS, you will get deployment failure with below detail: 
Web deployment task failed. (Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED

### How to deploy the function app directly from VS
the project’s with runtime v1, so you’d need to create/deploy to v1 Azure function app. And add the function runtime version in the csproj file: 
1.	Right click the project and edit the csproj file. 
2.	Add `<AzureFunctionsVersion>v1</AzureFunctionsVersion>` under `<PropertyGroup>`
 

To enable “Run from package file” option in Publish blade, 
1.	Right click the project and manage Nuget packages
2.	Update Microsoft.NET.Sdk.Functions to latest version (1.0.24). 
3.	Then you will see “Run from package file” in Publish blade. 

Then you'll be able to deploy the project to Azure with “Run from package file” enabled.

**Comment by DawnmarieDesJardins** [comment]
Hi Jerry,
I've assigned this to one of our authors to help you out.

**Comment by yeahsicy** [comment]
@DawnmarieDesJardins Thank you! 
I guess you probably need to update your function app project which seems out of date.

**Comment by DawnmarieDesJardins** [comment]
This one is scheduled for an update next month.  In the meantime, I'm willing to bet Chris will get you up and running in no time.

**Comment by joelhulen** [comment]
@yeahsicy , as @DawnmarieDesJardins said, this entire MCW is scheduled for an update this coming month. It was created a year ago, several months prior to Azure Functions v2 being GA'd. That's definitely one of the updates we'll include, among others. Keep a look out for issues here pertaining to updates in the next few weeks.

**Comment by DawnmarieDesJardins** [comment]
Hello!  Closing this issue as it was addressed in the recent update.
