### ISSUE TITLE
Exercise 3, Task 7 - Regarding Event Grid

### ISSUE THREAD

**Issue by wely** [Microsoft/MCW-Serverless-architecture#33]
Having the following error message upon click save instructed by the lab.
![image](https://user-images.githubusercontent.com/1658657/54518733-f923a000-499f-11e9-8b06-eb3be0cc51b1.png)

**Comment by joelhulen** [comment]
@wely , thanks for your feedback. I have recently updated this MCW and have submitted a pull request for review. During the update, I updated many screens you go through to configure the services, as much has changed recently on Azure, and have also made a lot of modifications to the code. There are no such issues in the latest update. I don't know if this is something you're going through on your own time or for a customer, but you could maybe consider checking out the changes in my PR before their merged into master, or perhaps wait until those changes are approved.

**Comment by DawnmarieDesJardins** [comment]
Hello!  Closing this issue as it was addressed in the recent update.
