### ISSUE TITLE
TollBothFunctionApp BlobTrigger not firing

### ISSUE THREAD

**Issue by MarchingBug** [Microsoft/MCW-Serverless-architecture#34]
Files are uploaded to the blob storage but function Process Image is not triggered, I tried to update Microsoft.Azure.Webjobs to version 3.0.0 as documentation indicates, I get this error

![serverlesserror](https://user-images.githubusercontent.com/11653125/55048862-21567300-5020-11e9-9c6d-81435be6c8fa.png)

Thank you in advance for all your help.

**Comment by joelhulen** [comment]
I have a PR pending containing updates that fixes this and adds new features, including moving to Functions v2.
