### ISSUE TITLE
Creation of Second Function App should use "node.js" Runtime Stack instead of Java script

### ISSUE THREAD

**Issue by Abhishekpathania01** [microsoft/MCW-Serverless-architecture#41]
Exercise 1 [Task 2](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-provision-the-function-apps) while creating the second Function App Lab guide says select **java script** for Runtime Stack but Currently we see that javascript is not available in Azure Portal, avaiable is only **java** but if we're selecting java then we're facing issues In Exercise 3 [Task 1](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-create-function-to-save-license-plate-data-to-azure-cosmos-db) **Create function to save license plate data to Azure Cosmos DB** 
**Step3 : In the blade menu, select Functions, the click + New Function.**

Here we need to create new Function but due to wrong Runtime stack selection while create of second Function App i.e. app whose name ends with Events, we're not able to view the option which is mentioned in **Step 4: Enter event grid into the template search form, then select the Azure Event Grid trigger template.**

When we're creating the function app with **node.js** Runtime stack then we're able to create new function as per the instructions mentioned in **Step 4: Enter event grid into the template search form, then select the Azure Event Grid trigger template.**

@DawnmarieDesJardins Could you please assign this ASAP, as we have a workshop schedued on Aug 15th. 

**Following needs to be changed:**

* Exercise 1 [Task 2](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-provision-the-function-apps) while creating the second Function App users should select **node.js** Runtime stack instead of java/ as javascript is not available in Azure portal. 

* Instructions for Create function to save license plate data to Azure Cosmos DB needs additional steps:
* Before Step 4 need instructions as mentioned below:
 4 (a). After clicking on  **+ New Function**, select In-Portal then click continue as shown in below image:
![image](https://user-images.githubusercontent.com/38715522/62956681-ffb02980-be10-11e9-9c01-a26df0888840.png)

4 (b). Select More templates
![image](https://user-images.githubusercontent.com/38715522/62956810-34bc7c00-be11-11e9-8d95-5789562a2658.png)

4 (c). Click on Finish and view template

Then users can continue from Step 4 mentioned in lab guide. 

Thanks in Advance
Abhishek Pathania

**Comment by DawnmarieDesJardins** [comment]
@givenscj @ZoinerTejada 
Hello!  Please review and advise.  Workshop is scheduled for 8/15 delivery.

**Comment by Abhishekpathania01** [comment]
Also, Please review all steps for Ex 3 [Task 1](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-create-function-to-save-license-plate-data-to-azure-cosmos-db) as there is miss-match of steps/screenshots. 

Such as:

Task 1:
1. Step 4; screenshot given for (a) and (b) should be interchanged, as the one with (a) belongs to (b) and vice-versa.
2. In Step 6 It says Replace the code in the new SavePlateData function with the following code. But it is not mentioned that after installing Azure Event Grid Trigger extension, it'll ask for new function creation where we need to enter SavePlateData as function name also no screenshot provided for this. Then step 6 should come to replace the code in the SavePlateData function. 

Task 2:
Step 1 and Step 2 are making confusion, only one step is sufficient we'd say step 2 as it has both steps and screenshot as well (step 1 is not needed)

Please review this as well. 

Thanks
Abhishek Pathania
