### ISSUE TITLE
September 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Serverless-architecture#44]
This MCW is scheduled for content update.
Solliance - please review current content and recommended updates for SME review.

**Comment by IshamMohamed** [comment]
[This image](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/media/saveplatedata-eg-sub.png) needs to be altered. There is no more "Subscribe to all event types" - if you just leave the event types to null, it does the same job.
