### ISSUE TITLE
Missing resource group

### ISSUE THREAD

**Issue by sandrich** [microsoft/MCW-Serverless-architecture#46]
Hi

The first step is to create a Storage account which require a resource group. But that is not part of the steps.

**Comment by joelhulen** [comment]
@sandrich The step to create the resource group is in the _Before the HOL_ guide. Did you complete that guide first? https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Serverless%20architecture.md
