### ISSUE TITLE
Issue on Exercise 1 (Task 1) and Exercise 2 (Task 4)

### ISSUE THREAD

**Issue by PrernaNagori09** [microsoft/MCW-Serverless-architecture#53]
1.  In [Exercise 1-Task 1](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-provision-the-storage-account) Issue with Storage name, Storage name have to be in small letters in document you give name as (tollboothstorageINIT).

2. In [Exercise 2-Task 4](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-4-finish-the-processimage-function#task-1-provision-the-storage-account) Issue with File Path, file path sould be clear like this("C:\TollBooth_Clean.zip\MCW-Serverless-architecture-master\Hands-on lab\starter\TollBooth").

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim
