### ISSUE TITLE
StatusCode: 404: 'Resource Not Found'. Wrong Vision API OCR URI.

### ISSUE THREAD

**Issue by inatale** [microsoft/MCW-Serverless-architecture#54]
Exercise 2->Task 4->Step 7. 
uriBase = Environment.GetEnvironmentVariable("computerVisionApiUrl"); is wrong (response is StatusCode: 404: 'Resource Not Found'.)

var uriBase = Environment.GetEnvironmentVariable("computerVisionApiUrl") + "vision/v2.1/ocr";

It should contain also "vision/v2.1/ocr".

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  

Having specific lab section references and screenshots will help expedite support. We will review your issue soon.

Tim

**Comment by joelhulen** [comment]
@inatale Thank you for submitting an issue. However, users are instructed to append `vision/2.0/ocr` at the end of the Vision API URL within Exercise 2, Task 1, Step 4: https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-configure-application-settings

Closing, as this is already addressed.

**Comment by inatale** [comment]
Oops. Yes, my fault. Thanks.
