### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by frankrutz** [microsoft/MCW-Serverless-architecture#57]
Thanks to the authors for this intro to Azure serverless architecture.

From a "cloud engineering" perspective, it would be nice to see this setup automated so it could live in a "gitops-spirit" environment. 

I will work on this a bit and hope to have a first version by the end of the year.
Never really worked with ARM, so this will take some time.
And it's a sparetime project to me.

Thanks again

**Comment by timahenning** [comment]
@frankrutz Thank you for the kind words.  It is not often we receive thanks.

Tim

**Comment by DawnmarieDesJardins** [comment]
@waltermyersiii 
FYI - spreading the well deserved kudos and kind words.  :)

**Comment by tyeth** [comment]
Hey all, thanks from the UK to the authors for this guide too. Just done this one to refresh a few things and tie a couple together. I would be keen to see the ARM template versions / cli versions too, but mostly I've realised the portal is easiest to create things with and then template based on them.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #89
