### ISSUE TITLE
Images to be updated in the lab guide

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Serverless-architecture#63]
[Exercise 1: Task 2:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-provision-the-function-apps) Step 10: Here **Version** needs to be added as shown below:

![image](https://user-images.githubusercontent.com/50323628/81439476-127f4100-918c-11ea-9627-3c797116dc4d.png)

[Exercise 1: Task 3:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-3-provision-the-event-grid-topic) Step 4: Now **Event Schema** is on the separate page from **Basics**:

![image](https://user-images.githubusercontent.com/50323628/81439627-48242a00-918c-11ea-8abf-443dad0c4486.png)

[Exercise 1: Task 4:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-4-provision-the-azure-cosmos-db-account) Step 3: There are new options available while creating Azure Cosmos DB Account, they are - **Apply Free Tier Discount,** **Account Type** and **Availability Zones.** 

![image](https://user-images.githubusercontent.com/50323628/81440323-7b1aed80-918d-11ea-98bd-8df4e31ef65a.png)

[Exercise 1: Task 4:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-4-provision-the-azure-cosmos-db-account) Step 7: **Indexing** is added as shown below:

![image](https://user-images.githubusercontent.com/50323628/81443092-5aa16200-9192-11ea-8132-1609acef216a.png)

[Exercise 1: Task 4:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-4-provision-the-azure-cosmos-db-account) Step 10 (d): To add throughput firstly you need to check ** Provision dedicated throughput for this container** box and then only you can add throughput.

![image](https://user-images.githubusercontent.com/50323628/81443644-693c4900-9193-11ea-9626-a2ad5483bb28.png)

[Exercise 1: Task 6:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-6-provision-azure-key-vault) Step 4: Screenshot needs to be updated.

![image](https://user-images.githubusercontent.com/50323628/81445308-3c3d6580-9196-11ea-8e79-0d4c9ccada30.png)

**Comment by DawnmarieDesJardins** [comment]
@SeeratArora 
Thanks for bringing this to our attention.  This workshop is scheduled for a June test/fix and we'll be updating images at that time.
