### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Serverless-architecture#64]

**Comment by joelhulen** [comment]
I recommend the following updates. Please provide feedback on the following:

1. Update all images used in the lab to correspond with the latest portal UI changes.
2. Update NuGet packages and SDKs to latest versions.
3. Update to Azure Functions 3.x runtime and .NET Core 3.1.
4. Add Azure DevOps to architecture diagram.

**Comment by waltermyersiii** [comment]
Looks good, Joel.

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  This update has been changed to a June test/fix.
