### ISSUE TITLE
Issue regarding Function App

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Serverless-architecture#65]
[Exercise 3: Task 4:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-4-create-function-to-save-manual-verification-info-to-azure-cosmos-db) Step 7: On saving the code it shows the following log.

![image](https://user-images.githubusercontent.com/50323628/82727742-fc37c000-9d09-11ea-8bbb-62339e4b4420.png)

[Exercise 3: Task 5:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-5-add-an-event-grid-subscription-to-the-queueplateformanualcheckup-function) Step 1: There's no button to **Add Event Grid subscription** as now we need to do it separately.

Step 2: When tried to separately add Event Grid Subscription, new point is that for:
a. Endpoint Type: Azure Function
b. Endpoint: Click on select endpoint. Now Select Azure Function window will appear, add following configurations there:
* Select your subscription from the drop-down.
* Select you Resource Group **serverless-architecture** from the drop-down.
* Function App: Select **TollBoothFunctionApp** from the drop-down.
* Slot: **Production**
* Function: Select **ProcessImage** from the drop-down.
* Then select **Confirm Selection** and **Create**.

[Exercise 4: Task 3:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-3-use-the-live-metrics-stream-to-monitor-functions-in-real-time) Step 10: Not getting the same output as shown in lab guide for Live Metrics in Application Insights.

![image](https://user-images.githubusercontent.com/50323628/82728292-22129400-9d0d-11ea-9f35-f106b8073e81.png)

[Exercise 5: Task 1:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-use-the-azure-cosmos-db-data-explorer) No documents fetched under Proccessed and NeedsManualReview collections.

![image](https://user-images.githubusercontent.com/50323628/82728352-62721200-9d0d-11ea-9328-9d9af783c5a0.png)

Can you please check?

Thanks,
Seerat

**Comment by akn9050** [comment]
Any update on this please?

**Comment by joelhulen** [comment]
@akn9050 the plan was to address this in the upcoming MCW update, once the plan was approved. However, I just learned that we will now do a test/fix instead of an update this time around. That said, I will address this sooner rather than later. Expect this and other issues to be resolved in the next week or two.
