### ISSUE TITLE
Outdated workshop?

### ISSUE THREAD

**Issue by andresu13** [microsoft/MCW-Serverless-architecture#66]
Hi, I am planning to deliver this workshop to one of my customers next week but it seems that some of the instructions and the screenshots are outdated - they no longer reflect what the portal looks like or the steps that need to be followed to accomplish certain tasks. So far I have been able to figure out most tasks but I got stuck on Exercise 2 - Task 5 (Adding EventGrid Subscription to the Function App). Are there any plans to update this workshop soon? Can I get in touch with someone internally (I am MSFT FTE) to get this running in my environment so I can deliver it to my customer next week?

Thank you!

**Comment by joelhulen** [comment]
This MCW is due for a test/fix this month. I'll update the instructions prior to your event next week. I'll be starting work on it today.

**Comment by andresu13** [comment]
Thanks a lot Joel. Looking forward to trying out the updated lab once you
are done :)
