### ISSUE TITLE
UI needs to be updated for function app publishing from visual studio

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-Serverless-architecture#68]
UI needs to be updated for function app publishing from visual studio, UI experience got changed when publishing function app from visual studio.

Ex 3 task 5 step 3 :

![image](https://user-images.githubusercontent.com/27498287/83933641-1375b380-a7c8-11ea-9b37-713ad679e845.png)

![image](https://user-images.githubusercontent.com/27498287/83933645-225c6600-a7c8-11ea-882c-8dfefbd0e56b.png)

![image](https://user-images.githubusercontent.com/27498287/83933648-26888380-a7c8-11ea-8e86-4df302aa0147.png)

**Comment by joelhulen** [comment]
@akn9050 what version of Visual Studio are you using? I have VS 2019 with the latest updates and the publishing screens I see match what's in the lab guide. I do not see the screens you posted above.

**Comment by akn9050** [comment]
I used latest VS 2019 vm, and I tried this Yesterday. 
            "publisher": "microsoftvisualstudio",
            "offer": "visualstudio2019latest",
            "sku": "vs-2019-comm-latest-ws2019",
            "version": "latest"
