### ISSUE TITLE
Exercise 2: Task 5:Not able to add Event Grid Subscription

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Serverless-architecture#70]
[Exercise 2: Task 5:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-5-publish-the-function-app-from-visual-studio) Step 11: The Integration flow is not similar for me as it is in the lab guide. Also there's a warning highlighted in the image below. Not sure why the warning message is there. 

![image](https://user-images.githubusercontent.com/50323628/84186852-c5ee9480-aaae-11ea-822b-f898369dbbd1.png)

Step 12: Not able to add Event Grid Subscription. I tried the way shown in the image below but this also didn't work.

![image](https://user-images.githubusercontent.com/50323628/84186179-c89cba00-aaad-11ea-8f84-a3cf72e90636.png)

Can you please look into this?

Thanks,
Seerat

**Comment by joelhulen** [comment]
@SeeratArora, when you look at your list of functions in the Function App, what do you see? The trigger type for `ProcessImage` should be **EventGrid**, as shown here:

![image](https://user-images.githubusercontent.com/5950304/84203170-f9adc800-aa76-11ea-9e5c-016dcce282a0.png)

**Comment by timahenning** [comment]
@SeeratArora Did you have a chance to review Joel's suggestion?

**Comment by SeeratArora** [comment]
Hi @timahenning 
I just tried going through the lab again and this time I didn't face this issue. I'm now able to create event subscription.

Thanks.

**Comment by timahenning** [comment]
That is great news.  We can reopen this issue if necessary.
