### ISSUE TITLE
CosmosDB Processed Table Empty

### ISSUE THREAD

**Issue by andresu13** [microsoft/MCW-Serverless-architecture#71]
There seems to be an issue with the lab. I have tried executing it multiple times and I always end up with an empty "Processed" table - no items at all. Can someone review the steps to make sure nothing is missing and/or ping me internally to discuss this? Thank you.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/8649312/84701777-9662e080-af23-11ea-9278-92c875bd9503.png)

**Comment by joelhulen** [comment]
@andresu13 I replied separately via email. I can connect with you directly and see if I can figure out why you are seeing this issue. My first thought is perhaps the Event Grid events are not triggering your functions. That's the first thing I recommend checking on your end.

**Comment by joelhulen** [comment]
We were able to resolve this issue by stepping through @andresu13's environment to find an incorrectly named Event Grid Topic event type filter name which prevented data with successful OCR processing to be routed to the functions that save this data in Cosmos DB.
