### ISSUE TITLE
HOL Exercise 4: Task 3: Step 13: Not able to run UploadImages project

### ISSUE THREAD

**Issue by bala1074** [microsoft/MCW-Serverless-architecture#72]
Followed exact same steps mentioned on HOL: https://cloudworkshop.blob.core.windows.net/serverless-architecture/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.html#serverless-architecture-hands-on-lab-step-by-step

Hands-On Lab Exercise 4: Task 3: Step 13: Not able to run UploadImages project, getting errors+warnings.
![ws_error](https://user-images.githubusercontent.com/12669425/87969910-99cc2780-cae0-11ea-9e24-1e9d1ad5bdfa.png)

**Comment by bala1074** [comment]
errors at
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Blob;
using Microsoft.Azure.Storage.DataMovement;

CloudStorageAccount and TransferManager

**Comment by joelhulen** [comment]
Are you able to right-click the `TollBooth` solution in Visual Studio's Solution Explorer, then select "Clean Solution", then "Rebuild Solution"? What happens when you do this? If you still see these errors, please paste the contents of the `packages.config` file from within the `UploadImages` project here.

**Comment by bala1074** [comment]
@joelhulen I tried, but still facing the same errors.
packages.config for UploadImages
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Azure.KeyVault.Core" version="3.0.4" targetFramework="net461" />
  <package id="Microsoft.Azure.Storage.Blob" version="11.0.1" targetFramework="net461" />
  <package id="Microsoft.Azure.Storage.Common" version="11.0.1" targetFramework="net461" />
  <package id="Microsoft.Azure.Storage.DataMovement" version="1.0.0" targetFramework="net461" />
  <package id="Microsoft.Azure.Storage.File" version="11.0.1" targetFramework="net461" />
  <package id="Microsoft.Data.Edm" version="5.8.4" targetFramework="net461" />
  <package id="Microsoft.Data.OData" version="5.8.4" targetFramework="net461" />
  <package id="Microsoft.Data.Services.Client" version="5.8.4" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="2.2.4" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.EnvironmentVariables" version="2.2.4" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.FileExtensions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Json" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Physical" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileSystemGlobbing" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Hosting" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Hosting.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Configuration" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options.ConfigurationExtensions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Primitives" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.20" targetFramework="net461" />
  <package id="Microsoft.Rest.ClientRuntime.Azure" version="3.3.19" targetFramework="net461" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="12.0.2" targetFramework="net461" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net461" />
  <package id="System.ComponentModel.Annotations" version="4.5.0" targetFramework="net461" />
  <package id="System.ComponentModel.EventBasedAsync" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.TraceSource" version="4.3.0" targetFramework="net461" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq.Queryable" version="4.3.0" targetFramework="net461" />
  <package id="System.Memory" version="4.5.3" targetFramework="net461" />
  <package id="System.Net.Requests" version="4.3.0" targetFramework="net461" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.2" targetFramework="net461" />
  <package id="System.Spatial" version="5.8.4" targetFramework="net461" />
  <package id="System.Threading.Tasks.Dataflow" version="4.9.0" targetFramework="net461" />
</packages>`

**Comment by joelhulen** [comment]
That looks correct. I just pulled a fresh copy of the repo down to test and it worked fine.

Do you have .NET Framework 4.61 or greater installed on your machine? <https://www.microsoft.com/net/download/windows>

**Comment by bala1074** [comment]
@joelhulen Please provide me the personal email, I'll share the RDP VM settings

**Comment by bala1074** [comment]
or we can have a quick call, please share me the link

**Comment by joelhulen** [comment]
@bala1074 I just emailed you.

**Comment by bala1074** [comment]
@joelhulen I sent to your mail, please have a look. thank you @joelhulen

**Comment by joelhulen** [comment]
I've figured out the problem.

Per the lab instructions, you must make sure you extract the files to `C:\ServerlessMCW`. Since you extracted the files to the Downloads folder instead (`C:\Users\workshop\Downloads\`), the file paths were too long for the project to successfully run, as seen in the following error in Visual Studio:

`Error occurred while restoring NuGet packages: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

I've extracted the project files to `C:\ServerlessMCW\`. Please continue your lab from that location.

**Comment by bala1074** [comment]
thank you @joelhulen
