### ISSUE TITLE
HOL: Azure Key-Valut service references are not working  

### ISSUE THREAD

**Issue by bala1074** [microsoft/MCW-Serverless-architecture#76]
![Screenshot from 2020-07-21 15-39-28](https://user-images.githubusercontent.com/12669425/88382076-5a922500-cdc5-11ea-95d7-0773282d66fd.png)

**Comment by bala1074** [comment]
I provided key-vault access to FunctionApp, so I temporarily fixed by hardcode the values at Function App. It works.

**Comment by joelhulen** [comment]
Please paste your string with the Cosmos DB path so I can validate you are using the proper format.

**Comment by timahenning** [comment]
Thank you for reporting this issue.  We are working to resolve your issue within the support time frame defined in https://microsoftcloudworkshop.com/.  If you have a workshop delivery coming up soon, leave a comment with details and we will try to resolve the issue sooner.  In the meantime, verify all task instructions have been followed and Azure environment is still valid.

Tim

**Comment by timahenning** [comment]
@bala1074 Hi, Joel is looking for more debug information in order to assist.  Can you provide the string he is looking for?  Otherwise, we will have to close this issue.

Thanks,

Tim

**Comment by bala1074** [comment]
Sorry, I cleaned up the workshop resources in Azure and Don't have screenshots. So, I will close this issue.
