### ISSUE TITLE
HOL: Not able to see the generated csv in storage

### ISSUE THREAD

**Issue by bala1074** [microsoft/MCW-Serverless-architecture#77]

**Comment by bala1074** [comment]
Continues deployment for Function App was not deploying the changes, but showing all commits at Azure Deployment Center, So I published manually with the latest changes then it's started working.

**Comment by joelhulen** [comment]
Can you please paste a screenshot of the Deployment Center?

**Comment by timahenning** [comment]
@bala1074 Hi, can you paste the screenshot into this issue?  Otherwise, I will have to close the issue.

Thanks,

Tim

**Comment by bala1074** [comment]
Sorry, I cleaned up the workshop resources in Azure and Don't have screenshots. So, I will close this issue.
