### ISSUE TITLE
September 2020 update suggestions

### ISSUE THREAD

**Issue by joelhulen** [microsoft/MCW-Serverless-architecture#78]
I recommend the following updates. Please provide feedback on the following:

- Update all images used in the lab to correspond with the latest portal UI changes
- Update NuGet packages and SDKs to latest versions
- Update to Azure Functions 3.x runtime and .NET Core 3.1
- Add GitHub Actions to the WDS and architecture diagram
- Add Durable Functions to WDS and use case scenario

**Comment by DawnmarieDesJardins** [comment]
Closing issue, update postponed
