### ISSUE TITLE
The OCR is not reading the plate number

### ISSUE THREAD

**Issue by eaelmoneem1** [microsoft/MCW-Serverless-architecture#79]
Does anybody know why the ocr is not reading the plate number from the same pics attached to the project files?
all the pictures are moving to NeedsManualReview.

**Comment by eaelmoneem1** [comment]
Additional update :
I have reviewed all the configurations in the portal and in the code. Also, I have modified this part manually and removed the else condition. Just to test that the event for "savePlateData" is working fine, and I was able to see data in CosmosDB "Processed" document but again with empty "licensePlateText" :

if (data.LicensePlateFound)
            {
                // TODO 3: Modify send method to include the proper eventType name value for saving plate data.
                await Send("savePlateData", "TollBooth/CustomerService", data);
            }
            else
            {
                // TODO 4: Modify send method to include the proper eventType name value for queuing plate for manual review.
                await Send("queuePlateForManualCheckup", "TollBooth/CustomerService", data);
            }

**Comment by eaelmoneem1** [comment]
@joelhulen @timahenning  Sorry guys for bothering you , But do you have any idea what could be the reason for the error up?
I have tried several things but with no luck

**Comment by joelhulen** [comment]
@eaelmoneem1 Sorry, I was away on vacation. Cold you please tell me what the value of your `computerVisionApiUrl` app setting is?

**Comment by eaelmoneem1** [comment]
Hi @joelhulen NP, thanks for looking into this.
The value for computerVisionApiUrl is: https://tollboothvisioninitlab.cognitiveservices.azure.com/vision/v2.0/ocr added in the Azure function

**Comment by joelhulen** [comment]
Thank you. When you look at your other App Settings, do you see the indicator that shows that the Key Vault reference was successfully retrieved? This will be for `computerVisionApiKey`, `eventGridTopicKey`, `cosmosDBAuthorizationKey`, and `blobStorageConnection`.

**Comment by eaelmoneem1** [comment]
I'm not sure exactly from where I can see this, But I think that all the connections are correct because  I have modified this part manually and removed the else condition. Just to test that the event for "savePlateData" is working fine, and I was able to see data in CosmosDB "Processed" document but again with empty "licensePlateText" :

if (data.LicensePlateFound)
            {
                // TODO 3: Modify send method to include the proper eventType name value for saving plate data.
                await Send("savePlateData", "TollBooth/CustomerService", data);
            }
            else
            {
                // TODO 4: Modify send method to include the proper eventType name value for queuing plate for manual review.
                await Send("queuePlateForManualCheckup", "TollBooth/CustomerService", data);
            }

and when i check the Function logs in the portal i see this logs for each file:

2020-09-16 12:13:52.738
Executing 'ProcessImage' (Reason='EventGrid trigger fired at 2020-09-16T12:13:51.5869921+00:00', Id=8607afca-fbcf-481c-b8cc-b93d738f007f)
Information

2020-09-16 12:13:53.011
Processing XVK7CDMI.jpg
Information

2020-09-16 12:13:53.196
Making OCR request
Information

2020-09-16 12:13:53.456
**Critical error: No MediaTypeFormatter is available to read an object of type 'OCRResult' from content with media type 'application/octet-stream'.
Critical**

2020-09-16 12:13:53.462
Finished OCR request. Result:
Information

2020-09-16 12:13:53.475
Sending license plate data to the queuePlateForManualCheckup Event Grid type
Information

2020-09-16 12:13:53.574
Sent the following to the Event Grid topic: TollBooth.Models.Event`1[TollBooth.Models.LicensePlateData]
Information

2020-09-16 12:13:53.575
Finished processing. Detected the following license plate:
Information

2020-09-16 12:13:53.604
Executed 'ProcessImage' (Succeeded, Id=8607afca-fbcf-481c-b8cc-b93d738f007f, Duration=2016ms)

**Comment by joelhulen** [comment]
Can you please update the `GetImageHttpContent` method of the `FindLicensePlateText.cs` file (https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/starter/TollBooth/TollBooth/FindLicensePlateText.cs#L103) by replacing `content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");` with `content.Headers.ContentType = new MediaTypeHeaderValue("application/application/json");` or `text/plain` if that doesn't work?

**Comment by eaelmoneem1** [comment]
This is strange, I deleted the function from the portal and then I made the changes and published it.
But I keep receiving the same error :
**Critical error: No MediaTypeFormatter is available to read an object of type 'OCRResult' from content with media type 'application/octet-stream'.**

I have tried (application/json) & (text/plain)

**Comment by eaelmoneem1** [comment]
The issue has been resolved. The problem was in one of the KeyVault keys.
Thanks for your help
