### ISSUE TITLE
Could not build tollbooth project from VS.

### ISSUE THREAD

**Issue by rajredd** [microsoft/MCW-Serverless-architecture#83]
I have installed Visual Studio 2019 community 16.8.2 version and dotnet 5.0.1. I was not able to build tollbooth project from VS.

see the errors from the screen shot. 

![image](https://user-images.githubusercontent.com/37375319/100036601-84d50d00-2dce-11eb-8219-ffe4fc3a6d1e.png)

![image](https://user-images.githubusercontent.com/37375319/100036636-928a9280-2dce-11eb-8950-34a73d3e6fee.png)

the link shown from VS (NETSDK1) above pointed to https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1005?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1005);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.6.1)%26rd%3Dtrue

According to the link, the issue should have been fixed in VS 16.8 and .NET 5. Can someone help to give it a try? Thanks.

**Comment by joelhulen** [comment]
You must install .NET Core 3.1, per the pre-requisites. The TollBooth.cs project has `<TargetFramework>netcoreapp3.1</TargetFramework>` set, denoting that you must have .NET Core 3.1 installed on your machine to successfully build.

Please try this out and let us know if it works.

**Comment by rajredd** [comment]
The issue did not seem to be related to the installation of .NET Core 3.1. My system has both 3.1 and 5.0 versions installed. After read this link  'https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows' ; I removed 'NuGet fallback folder' under 'C:\Program Files\dotnet\sdk'; build was successful now. :-)
