### ISSUE TITLE
Data is not visible in Cosmos DB

### ISSUE THREAD

**Issue by raphasi** [microsoft/MCW-Serverless-architecture#86]
Hello, first I would like to thank you for the laboratory created, rich in details and technologies, a great job. I followed the step-by-step exactly as described (I even did it twice from scratch), however, the data is not appearing in Cosmos DB, the image files appear inside my Blob, but not in DB. Do you have any idea what I might be doing wrong? I know that the environment has many details, but I am not able to identify where I am wrong. I appreciate the help, I would love to successfully complete the lab. Thanks

**Comment by joelhulen** [comment]
Thank you @raphasi!

Usually when this happens, it has to do with the Event Grid configuration. Please verify that the source code for the .NET function app is sending the events correctly, then make sure that the Event Grid subscription on the Node.js function app side is properly configured to monitor and process successful and failed events. When you open App Insights, do you see the functions firing as images upload? If so, make sure the Event Grid portions are all properly configured. It's possible to "fat finger" topic names and the like, so copy and paste from the instructions wherever you can.

**Comment by raphasi** [comment]
Thanks @joelhulen  for the quick response.

Whenever possible, use the same name in the Functions and Event Grid settings. In the code used in VS is it necessary to make any changes if I am using the same resource names? Did not make altered changes, just published and had no error return.

When uploading images, validate an error in Application Insights "cannot find function: 'ProcessImage', available function names: []"
However, if I go to the Function App ToolBoothFunctionApp I see the Functions "ExportLicensePlates" and "ProcessImage". If I access these functions, the monitoring shows all execution counters as 0.

**Comment by raphasi** [comment]
@joelhulen 

I just reviewed every step by step and saw that I didn't change the code in Visual Studio - TODO 1, 2, 3 and 4.
I am going to recreate the LAB and I believe it will solve my problem.

Thank you very much

**Comment by joelhulen** [comment]
That is your problem then. The function is not sending the Event Grid event for the other functions to use to update Cosmos DB. Please let me know if you get it working.

**Comment by raphasi** [comment]
Thanks for support @joelhulen!
