### ISSUE TITLE
Instruction and Screenshot Update

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Serverless-architecture#88]
[Exercise1 Task1](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-provision-the-storage-account)

**Step 7** : Instruction and Screenshot Update

On the Storage account blade, select Access Keys, under Settings in the menu. Then on the Access keys blade, click on **Show Keys** then select the Click to copy button for key1 connection string.

**Step 9** : Instruction and Screenshot Update

Select Containers under Blob Service in the menu. Then select the + Container button to add a new container. In the Name field, enter images, select Private (no anonymous access) for the public access level, then select **Create** to save.

**Step 10** : Screenshot Update

[Exercise1 Task2](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-provision-the-function-apps)

**Step 4** : Instruction and Screenshot Update

Runtime stack should be changed from **.NET Core** to **.NET** in the instruction.

**Step 6** : Screenshot Update

**Step 8** : Instructions were not provided in the lab guide to create a new **Worskpace** while creating **Application Insights**

**Step 11** : Instruction and Screenshot Update

Version should be updated from **12** to **12LTS** in the instruction.

**Step 9,11** : Screenshot Update

[Exercise1 Task4](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-4-provision-the-azure-cosmos-db-account)

**Step 3,16** : Screenshot Update

[Exercise1 Task6](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-6-provision-azure-key-vault)

**Step 4** : Instruction has to be updated from **Retention period (days): Leave at 90** to Days to **retain deleted vaults: Leave at 90**

Screenshot needs to be update.

[Exercise3 Task1](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-create-function-to-save-license-plate-data-to-azure-cosmos-db)

**Step 4,5** : Instruction and Screenshot Update

[Exercise3 Task4](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-4-create-function-to-save-manual-verification-info-to-azure-cosmos-db)

**Step 2,3** : Instruction and Screenshot Update

[Exercise6 Task1](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-create-the-logic-app)

**Step 4** : Screenshot Update

[Exercise7 Task2](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-configure-your-function-app-to-use-your-github-repository-for-continuous-deployment)

**Step 3** : UI has been updated and didn't find **Github** option on the **Deployment Center** blade  instead found the option on the **Deployment Center(Classic)** blade.

**Comment by timahenning** [comment]
Hi @tejaswini972,

This MCW is going through an update.  We will review your listed items during the update.

Thanks,

Tim

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #89
