### ISSUE TITLE
Within Task 2: Finish the ProcessImage function Incomplete TODO

### ISSUE THREAD

**Issue by archanamehta** [Microsoft/MCW-Serverless-architecture#9]
Hi,
   Once I open theTollBooth project within VS , I do not have all the necessary Code to Enter within TODO. For example: What do I enter for databaseMethod.cs? The Code does not seem to work. Can someone Assist? 

Regards,
Archana

**Comment by joelhulen** [comment]
Are you following the HOL step-by-step guide? You'll see the code for databaseMethods.cs: https://github.com/Microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-finish-the-processimage-function

**Comment by archanamehta** [comment]
I do see the code to enter for DatabaseMethod.cs for TODO 5. What do I enter? 

// TODO 5: Retrieve a List of LicensePlateDataDocument objects from the collectionLink where the exported value is false.
 // COMPLETE: licensePlates = _client.CreateDocumentQuery ...
 // TODO 6: Remove the line below.
 licensePlates = new List<LicensePlateDataDocument>();

**Comment by archanamehta** [comment]
Also When I open the Code is VS I get errors and not sure what needs to be done.

**Comment by joelhulen** [comment]
You can find the code for TODO 5 here:

https://github.com/Microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-4-finish-your-exportlicenseplates-function-code-and-push-changes-to-github-to-trigger-deployment

The code in VS is supposed to throw errors until the TODO items are completed in order, per the instructions in the doc above.

**Comment by archanamehta** [comment]
Got the VS Code , Now when I publish I only get option for Folder and not Azure functions. Am I missing something here?

**Comment by joelhulen** [comment]
Read the Before-the-lab instructions on what system requirements are. I suspect you lack the appropriate Visual Studio update version: https://github.com/Microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Serverless%20architecture.md

**Comment by DawnmarieDesJardins** [comment]
Closing issue, completed.
