### ISSUE TITLE
Logic App Cannot convert undefined or null to object error

### ISSUE THREAD

**Issue by riwasa** [microsoft/MCW-Serverless-architecture#91]
When opening the Logic App in the portal, the following error is shown:

![LogicApp](https://user-images.githubusercontent.com/8047495/118127270-781d9300-b3c7-11eb-8236-665aa9028f62.png)

I can consistently reproduce this when using the ARM template out of this repo. I believe the problem is with the Logic App definition. The current ARM template has the following:

`
{
      "name": "[variables('logicAppName')]",
      "type": "Microsoft.Logic/workflows",
      "apiVersion": "2016-06-01",
      "location": "[variables('location')]",
      "properties": {
        "definition": {
          "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {}
      }
    }
`

If you add "parameters", "actions", "triggers", and "outputs" to the definition, then the portal error does not occur and the Logic App designer will come up correctly:
`
    {
      "name": "[variables('logicAppName')]",
      "type": "Microsoft.Logic/workflows",
      "apiVersion": "2016-06-01",
      "location": "[variables('location')]",
      "properties": {
        "definition": {
          "contentVersion": "1.0.0.0",
          "parameters": {},
          "actions": {},
          "triggers": {},
          "outputs": {},
          "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#"
        },
        "parameters": {}
      }
    }
`

**Comment by daronyondem** [comment]
I was able to reproduce. Thanks for the fix @riwasa
