### ISSUE TITLE
Cosmos DB collections cannot be viewed in the portal

### ISSUE THREAD

**Issue by riwasa** [microsoft/MCW-Serverless-architecture#92]
The definition of the Cosmos DB account in the ARM template includes the following:

`
"networkAclBypass": "AzureServices",
"publicNetworkAccess": "Disabled"
`

This causes an issue in the portal with viewing collections even after a local client IP address is added to the firewall.

The following error comes up on the overview blade:

![CosmosDB04](https://user-images.githubusercontent.com/8047495/118128210-95069600-b3c8-11eb-9281-b5b07b387723.png)

Trying to view a collection indicates the local IP is blocked by the firewall:

![CosmosDB05](https://user-images.githubusercontent.com/8047495/118128249-a64fa280-b3c8-11eb-86d6-7eeab5f5134c.png)

But if I go to the firewall and virtual networks settings, the same local IP is indeed marked as allowed:

![CosmosDB06](https://user-images.githubusercontent.com/8047495/118128273-ad76b080-b3c8-11eb-8774-325e3ed20bc9.png)

If you change the Cosmos DB definition in the ARM template to the following so it does not try to apply network restrictions without actually setting any IP addresses, then go into the Cosmos firewall in the portal, and then turn on restrictions there, it works fine.

`
      "properties": {
        "consistencyPolicy": {
          "defaultConsistencyLevel": "Session"
        },
        "locations": [
          {
            "locationName": "[variables('location')]"
          }
        ],
        "databaseAccountOfferType": "Standard",
        "enableAutomaticFailover": false,
        "enableFreeTier": false,
        "enableAnalyticalStorage": false,
        "enableMultipleWriteLocations": false
      },
`

**Comment by daronyondem** [comment]
Hi @riwasa 

There is something wrong with the propagation of the firewall settings. The [suggested maximum wait time is 15 minutes](https://docs.microsoft.com/bs-latn-ba/azure/cosmos-db/troubleshoot-forbidden). However, I still had the issue after 60 minutes of wait. I will investigate this with the product team before heading over and removing the firewall settings from the CosmosDB account in the lab. 

I will keep you updated. Thanks for reporting the issue. Appreciated.

**Comment by riwasa** [comment]
Thanks @daronyondem. FYI, I've got a Cosmos DB account that was created on Wednesday that is still showing the issue.
