### ISSUE TITLE
Deployment center now default to .Net version 4

### ISSUE THREAD

**Issue by ricardocovo** [microsoft/MCW-Serverless-architecture#98]
While completing the lab today, the deployment center did not give me the option to select the .Net version but instead defaulted it to version 4 as shown below:

![Screenshot 2021-08-31 104643](https://user-images.githubusercontent.com/1675545/131558275-fd495d58-742f-4566-8015-5a36c3db40b2.png)

As a result, the git action failed as follow:

![image](https://user-images.githubusercontent.com/1675545/131558378-dd1581bd-9dcf-4876-83e6-26752a5c3a4d.png)

I resolved this issue by manually changing the version in the YAML, but it might be confusing for lab participants.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #100
