### ISSUE TITLE
Unbale to change .Net version which has set default to v4.0.

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Serverless-architecture#99]
1. Issue in [Exercise 6, Task 2, Step 8](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-configure-your-function-app-to-use-your-github-repository-for-continuous-deployment) As UI got updated in Azure portal, users are not able to select .Net version 3.1 inside function app for connecting to GitHub, which has set to default v4.0 leading failure to Add or update the App Service in GitHub.

![image](https://user-images.githubusercontent.com/83394010/131660211-ccd2785e-2893-4bc4-b26e-4769e3dc6600.png)

   > Note: Resolved the issue by updating the version in YAML file manually, but it will be difficult to the users to do this.

2. Encountered multiple screenshot issues for Function App and Logic App.

**Comment by ricardocovo** [comment]
@Karthikkc123  I reported the same issue yesterday. 

If you want to continue with the lab, you need to change the deployment file manually and change the .net version and that will allow you to continue with the exercise.

The file you need to change would be in your repository, and the change is just as follow:
![image](https://user-images.githubusercontent.com/1675545/131673261-6dae6dd4-cb67-4456-a37e-a13376970249.png)

FYI. check this other issue I reported about a problem with the ExportLicensePlates function: https://github.com/microsoft/MCW-Serverless-architecture/issues/97

Hope this helps,

**Comment by Karthikkc123** [comment]
Thanks @ricardocovo, I have checked on that.
Even I have done the same by updating the DOTNET_VERSION manually.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #100
